apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://35.200.216.39
  name: gke_projects-419913_asia-south1_cluster-1
contexts:
- context:
    cluster: gke_projects-419913_asia-south1_cluster-1
    user: gke_projects-419913_asia-south1_cluster-1
  name: gke_projects-419913_asia-south1_cluster-1
current-context: gke_projects-419913_asia-south1_cluster-1
kind: Config
preferences: {}
users:
- name: gke_projects-419913_asia-south1_cluster-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
